name: Deploy

on:
  release:
    types: [released]

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy:
    needs: [ build ]
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.event.release.tag_name }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x' # SDK Version to use.
      - name: prepare version
        run: |
          echo "$VERSION"
      - name: pack Tinkoff.Visor
        run: |
          cd src
          dotnet pack Tinkoff.Visor/Tinkoff.Visor.csproj -c Release  /p:PackageVersion=${{env.VERSION}}
      - name: pack Tinkoff.Visor.Gen
        run: |
          cd src
          dotnet pack Tinkoff.Visor.Gen/Tinkoff.Visor.Gen.csproj -c Release  /p:PackageVersion=${{env.VERSION}}
      - name: pack Tinkoff.Visor.Gen.FSharp
        run: |
          cd src
          dotnet pack Tinkoff.Visor.Gen.FSharp/Tinkoff.Visor.Gen.FSharp.csproj -c Release  /p:PackageVersion=${{env.VERSION}}
      - name: publish
        run: |
          cd src
          dotnet nuget push **/Tinkoff.Visor.*.nupkg -k ${{secrets.NUGET_APIKEY}} -s https://www.nuget.org